version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban-app-api
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
      - "443:443"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./certs:/usr/src/app/certs
    depends_on:
      - postgres
    networks:
      - kanban-network

  postgres:
    image: postgres:15-alpine
    container_name: kanban-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanban-network

networks:
  kanban-network:
    driver: bridge

volumes:
  postgres_data: